### ISSUE TITLE
Small error in deinitializing opus ( plgopus.c )

### ISSUE THREAD

**Issue by Kaosumaru** [sipXtapi/sipXtapi-svn-mirror#1]
Opus encoder is being destroyed by opus_decoder_destroy, and vice versa.

```
opus_encoder_destroy(codecContext->mpDecoderContext);
opus_decoder_destroy(codecContext->mpEncoderContext);
```

This isn't very important, because currently those functions are interchangeable (they both call opus_free), but this can change someday.

**Comment by dgpetrie** [comment]
Thanks for pointing this out.  This is fixed.
